server:
  port: 9090

spring:
  h2:
    console:
      enabled: true

key:
  pageToken: PAGE_TOKEN
  userToken: USER_TOKEN
  pageId: 100089951486236_pfbid04i2Uj51mVpDmpBnKTaMNHdXwrEheTmAbyf8buUN123jVDhB7UskwJ6rM7uon6iEQl
  userId: 100090289271363
  apiUri: https://graph.facebook.com/
  queryString: ?method=GET&access_token=